# Generated by Django 4.1.3 on 2022-12-03 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test01', '0002_test02'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test02',
        ),
    ]
